### ISSUE TITLE
_parse() treats 'misc' as datetime

### ISSUE THREAD

**Issue by ElHeffeVonPhennig** [ZEDGR/pychallonge#15]
In api.py the list of string values to treat as text do not include 'misc', which is provided in response to the participant.bulk_add() and index() calls. The API documentation states that 'misc' is user generated string value. Attempts to parse this as a datetime field can alter the fields value.

**Comment by ZEDGR** [comment]
Thanks for this. The latest version [1.11.5](https://github.com/ZEDGR/pychallonge/releases/tag/1.11.5) is converting the "misc" field only to string.
