### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by jithinsss** [ZEDGR/pychallonge#6]
Not entirely sure whats up, but all the sudden I have been getting 502 Bad Gateway

**Comment by mahousenshi** [comment]
Not this lib user but I'm getting it too so its maybe a issue is on challonge side. I tried to contact support yesterday (25/03) but without response.

**Comment by russellvt** [comment]
I'm thinking challonge decided to change their API so-as to force {username}:{password}@api.challonge.com, since my BASH scripts still work with the same key, and using curl. Chances are they "broke" their htpasswd method, or something. Ideally, this module should probably support both methods.

**Comment by russellvt** [comment]
I have also verified that all tests are failing from current commit (https://github.com/ZEDGR/pychallonge/commit/33aceea6be556242f735d0da89aa6d9762e3e84e).

**Comment by ZEDGR** [comment]
Thanks for mentioning this. I am working on a fix

**Comment by ZEDGR** [comment]
A new version with the fix is now available (1.11.1) For more info check the PR #7

**Comment by russellvt** [comment]
Thanks for the quick fix... I had traced it down, as well, and was about to push a fix to my fork ... then came back here and saw you had already done it! LOL
