### ISSUE TITLE
Attribute Error: No attribute set_credentials

### ISSUE THREAD

**Issue by jithinsss** [ZEDGR/pychallonge#9]
Getting an error

AttributeError: module 'challonge' has no attribute 'set_credentials'

**Comment by ZEDGR** [comment]
I have just tested in a fresh virtualenv and the module is working fine. Please do the following:

1. Setup a new virtualenv
2. Use the pychallonge module `pip install pychallonge`. Check that you have installed the latest version 1.11.1 with `pip list`
3. Check again the set_credentials function

If the issue persists please provide the following information:
- OS/Platform (Windows, Linux, etc)
- Python version
- PIP version

**Comment by jithinsss** [comment]
Ahh yea, that was actually my fault.
